config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tweets#top'
  get 'tweets/index' => 'tweets#index'
  get 'tweets/new' => 'tweets#new'
  post 'tweets/create' => 'tweets#create', as: :tweets
  get 'tweet/:id/edit' => 'tweets#edit', as: :tweet_edit
  patch 'tweet/:id/update' => 'tweets#update', as: :tweet
  delete 'tweet/:id/destroy' => 'tweets#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :content, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :nickname, presence: true

  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    added_attrs = [ :nickname, :email, :password, :password_confirmation]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :new, :show]
  def top
  end

  def index
    @tweets = Tweet.all.order(created_at: :desc)
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.create(tweet_params)
    redirect_to("/tweets/index")
  end

  def edit
    @tweet = Tweet.find_by(id: params[:id])
  end

  def update
    @tweet = Tweet.find_by(id: params[:id])
    @tweet.update(tweet_params)
    redirect_to('/tweets/index')
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to("/tweets/index")
  end


  private
  def tweet_params
    params.require(:tweet).permit(:content, :category, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SNS</title>
    <%= csrf_meta_tags %>
    <meta  name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
       <div style="width: 100%;  height: 100px; padding-top: 20px; text-align: center; background-color: skyblue">
         <h1 >Welcome to MySNS</h1>
       </div>
      <div style="text-align: right;">
        <% if user_signed_in?%>
          <%= link_to("Top","/") %>
          <%= link_to("Tweet Index","/tweets/index") %>
          <%= link_to("New Tweet","/tweets/new") %>
          <%= link_to("ログアウト","/users/sign_out", method: :delete, date:{ confirm: "本当にログアウトしますか？"}) %>
        <% else %>
          <%= link_to("Top","/") %>
          <%= link_to("会員登録","/users/sign_up") %>
        <% end %>
      </div>
    </header>

    <p class="alert alert-success" style="text-align: center">
      <%= notice %>
    </p>
    <p class="alert alert-danger" style="text-align: center">
      <%= alert %>
    </p>
    <%= yield %>
  </body>
</html>

app/views/tweets/edit.html.erb
<h3 style="text-align: center">Edit Tweet</h3>

<%= form_for @tweet do |f| %>
    <%= f.text_area :content %><br>
    <%= f.label :"Category" %><br>
    <%= f.select :category, [["Sports","sports"] ,["Technology","technology"] ,["Gourmet","gourmet"]] %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.submit(["Up date"]) %>
<% end %>

app/views/tweets/index.html.erb
<h3 style="text-align: center">Tweet Index</h3>

<table style="margin: 0 auto;">
  <thead>
    <tr>
      <th style="text-align: center; padding: 5px 10px; width: 10%">Category</th>
      <th style="padding: 5px 10px; width: 60%">Tweets</th>
      <th style="text-align: center; padding: 5px 10px; width: 15%">Nickname</th>

    </tr>
  </thead>

  <tbody>
  <%# binding.pry %>
    <% @tweets.each do |tweet| %>
      <tr>
        <td style="text-align: center; padding: 30px 10px; width: 10%"><%= tweet.category %></td>
        <td style="padding: 5px 10px; width: 60%"><%= tweet.content %></td>
        <td style="text-align: center; padding: 5px 10px; width: 15%"><%= tweet.user.nickname %></td>
        <% if tweet.user_id == current_user.id %>
          <td style="text-align: center; padding: 5px 5px; width: 5%"><%= link_to("編集",tweet_edit_path(tweet.id)) %></td>
          <td style="text-align: center; padding: 5px 5px; width: 5%"><%= link_to("削除","/tweet/#{tweet.id}/destroy", method: :delete) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tweets/new.html.erb
<h3 style="text-align: center">New Tweet</h3>

<%= form_for @tweet do |f| %>
    <%= f.text_area :content %><br>
    <%= f.label :"Category" %><br>
    <%= f.select :category, [["Sports","sports"] ,["Technology","technology"] ,["Gourmet","gourmet"]] %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.submit(["Tweet"]) %>
<% end %>

app/views/tweets/top.html.erb
<h3 style="text-align: center;">Top</h3>


<% if user_signed_in? %>
  <p style="text-align: center;">ログイン中</p>
<% else %>
  <p style="text-align: center;"><%= link_to("ログイン","/users/sign_in") %>
  <%= link_to("会員登録","/users/sign_up") %></p>
<% end %>